export const ADMIN_LOGS_REQUEST = 'ADMIN_LOGS_REQUEST';
export const ADMIN_LOGS_SUCCESS = 'ADMIN_LOGS_SUCCESS';
export const ADMIN_LOGS_FAIL = 'ADMIN_LOGS_FAIL';
export const ADMIN_LOGS_RESET = 'ADMIN_LOGS_RESET';

export const ALL_USERS_LIST_REQUEST = 'ALL_USERS_LIST_REQUEST';
export const ALL_USERS_LIST_SUCCESS = 'ALL_USERS_LIST_SUCCESS';
export const ALL_USERS_LIST_FAIL = 'ALL_USERS_LIST_FAIL';
export const ALL_USERS_LIST_RESET = 'ALL_USERS_LIST_RESET';
