export const ADMIN_LOGS_REQUEST = 'ADMIN_LOGS_REQUEST';
export const ADMIN_LOGS_SUCCESS = 'ADMIN_LOGS_SUCCESS';
export const ADMIN_LOGS_FAIL = 'ADMIN_LOGS_FAIL';
export const ADMIN_LOGS_RESET = 'ADMIN_LOGS_RESET';
