export const COMPANY_LOGIN_REQUEST = 'COMPANY_LOGIN_REQUEST';
export const COMPANY_LOGIN_SUCCESS = 'COMPANY_LOGIN_SUCCESS';
export const COMPANY_LOGIN_FAIL = 'COMPANY_LOGIN_FAIL';
export const COMPANY_LOGOUT = 'COMPANY_LOGOUT';

export const COMPANY_REGISTER_REQUEST = 'COMPANY_REGISTER_REQUEST';
export const COMPANY_REGISTER_SUCCESS = 'COMPANY_REGISTER_SUCCESS';
export const COMPANY_REGISTER_FAIL = 'COMPANY_REGISTER_FAIL';

export const COMPANY_PROFILE_REQUEST = 'COMPANY_PROFILE_REQUEST';
export const COMPANY_PROFILE_SUCCESS = 'COMPANY_PROFILE_SUCCESS';
export const COMPANY_PROFILE_FAIL = 'COMPANY_PROFILE_FAIL';
export const COMPANY_PROFILE_RESET = 'COMPANY_PROFILE_RESET';

export const COMPANY_SYSTEMS_REQUEST = 'COMPANY_SYSTEMS_REQUEST';
export const COMPANY_SYSTEMS_SUCCESS = 'COMPANY_SYSTEMS_SUCCESS';
export const COMPANY_SYSTEMS_FAIL = 'COMPANY_SYSTEMS_FAIL';
export const COMPANY_SYSTEMS_RESET = 'COMPANY_SYSTEMS_RESET';

export const COMPANY_PROFILE_UPDATE_REQUEST = 'COMPANY_PROFILE_UPDATE_REQUEST';
export const COMPANY_PROFILE_UPDATE_SUCCESS = 'COMPANY_PROFILE_UPDATE_SUCCESS';
export const COMPANY_PROFILE_UPDATE_FAIL = 'COMPANY_PROFILE_UPDATE_FAIL';
export const COMPANY_PROFILE_UPDATE_RESET = 'COMPANY_PROFILE_UPDATE_RESET';

export const COMPANY_PROFILE_DELETE_REQUEST = 'COMPANY_PROFILE_DELETE_REQUEST';
export const COMPANY_PROFILE_DELETE_SUCCESS = 'COMPANY_PROFILE_DELETE_SUCCESS';
export const COMPANY_PROFILE_DELETE_FAIL = 'COMPANY_PROFILE_DELETE_FAIL';
export const COMPANY_PROFILE_DELETE_RESET = 'COMPANY_PROFILE_DELETE_RESET';
