export const SYSTEM_LIST_REQUEST = 'SYSTEM_LIST_REQUEST';
export const SYSTEM_LIST_SUCCESS = 'SYSTEM_LIST_SUCCESS';
export const SYSTEM_LIST_FAIL = 'SYSTEM_LIST_FAIL';
export const SYSTEM_LIST_RESET = 'SYSTEM_LIST_RESET';
